### ISSUE TITLE
希望能加入对RecyclerView的支持

### ISSUE THREAD

**Issue by waylent** [wangzhzh/AutoTrackAppClick1#1]
为什么没有提到RecyclerView呢?
PS.我买了你的书，真的是太巧了，刚接到无痕埋点的任务，就发现2019年2月有人出版了一本Android方面埋点的书，实在是太幸运了，内容挺新的，我买的亚马逊电子书，全平台同步，看着太爽了，感谢作者的努力与付出，做着相关生意还愿意开源

**Comment by wangzhzh** [comment]
你可以加我QQ详细讨论一下：598594711

**Comment by wangzhzh** [comment]
RecyclerView 没有 setOnItemClickListener，它的 item 点击和普通 View 的点击是完全一样的，所以无需做特殊处理即可支持。
